### ISSUE TITLE
Recuperación del trabajo

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-bigmamadata#10]
Tenéis una nueva issue para resumir las cosas que debéis **mejorar de cara a aprobar el trabajo**.

- Debéis limpiar el repositorio y dejar UN SOLO FICHERO PRINCIPAL.
- Debéis aseguraros de usar una librería vuestra, aunque sea sencilla.
- Tenéis que hacer un nuevo diagrama de flujo que refleje lo que habéis hecho y no lo que querríais hacer.
- Tenéis que aseguraros de tener al menos una estructura de datos con varias variables y usarla para algo, aunque sea simple
- Tenéis que hacer lectura y escritura de ficheros para algo, aunque sea sencillo.
- En la wiki, debéis hablar comentar el funcionamiento del programa además de explicar las partes del código más importantes.

Para que cuente el trabajo como aprobado, **debéis participar en las mejoras, no vale que lo acabe una persona y el resto no haga nada. Quién no participe, su nota no se actualizará**. En vuestro caso, además, hay un integrante que prácticamente no ha hecho nada del trabajo hasta la fecha, y así ha quedado reflejado en la nota. Si no cambia nada para extraordinaria no aprobará aunque entre los demás si acabéis el trabajo.

**FECHAS**: el límite de entrega de la recuperación del trabajo en convocatoria extraordinaria sería el día del examen a las 23:59.

Cuando acabéis, cerrad esta issue para dejarlo marcado.

**Comment by davizinho5** [comment]
Harán las mejoras para el aprobado únicamente Pablo y Alejandro.

**Comment by davizinho5** [comment]
Debéis terminar de poner bien la librería, eliminar varias de los warnings que aparecen el compilar y limpiar el código en general.

**Comment by alejandromgarces** [comment]
todo cerrado y perfecto
